%% ============================================================
% EEE3094S LAB 1
% SYSTEM IDENTIFICATION - FREQUENCY RESPONSE
%
% Student: Junaid Pieters
%
% This script:
% 1. Finds the experimental frequency-test CSV files automatically
% 2. Extracts the sinusoidal input and output signals
% 3. Removes initial transient behaviour
% 4. Fits sinusoids to the measured signals
% 5. Calculates magnitude and phase
% 6. Produces measured Bode plots
% 7. Estimates a frequency-domain second-order model
% 8. Compares it with the step-response model
% 9. Produces model-validation plots
% 10. Saves processed data and figures
%
% Requires:
% MATLAB Control System Toolbox
%% ============================================================

clc;
clear;
close all;

%% ============================================================
% 1. LOCATE REPOSITORY
%% ============================================================

% Folder containing this MATLAB script
matlabFolder = fileparts(mfilename('fullpath'));

% Parent folder = repository root
repoFolder = fileparts(matlabFolder);

% Expected frequency-test data folder
dataFolder = fullfile( ...
    repoFolder, ...
    'data', ...
    'frequency_test');

% Figures output folder
figureFolder = fullfile( ...
    repoFolder, ...
    'figures');

if ~exist(figureFolder, 'dir')
    mkdir(figureFolder);
end


fprintf('\n');
fprintf('=============================================\n');
fprintf('EEE3094S LAB 1 - FREQUENCY RESPONSE\n');
fprintf('=============================================\n\n');

fprintf('MATLAB script folder:\n%s\n\n', matlabFolder);

fprintf('Repository folder:\n%s\n\n', repoFolder);

fprintf('Expected data folder:\n%s\n\n', dataFolder);


%% ============================================================
% 2. FREQUENCIES USED IN YOUR LAB
%% ============================================================

% Your experimental frequencies in rad/s
expectedFrequencies = [ ...
    0.5
    0.8
    1.0
    1.4
    1.8
    2.2
    3.0
    5.0
    8.0
    ];

numberExpected = length(expectedFrequencies);


%% ============================================================
% 3. SEARCH FOR FREQUENCY CSV FILES
%% ============================================================

% First search expected folder
csvFiles = [];

if exist(dataFolder, 'dir')

    csvUpper = dir(fullfile(dataFolder, '*.CSV'));
    csvLower = dir(fullfile(dataFolder, '*.csv'));

    csvFiles = [csvUpper; csvLower];

end


%% ------------------------------------------------------------
% If nothing found, search entire repository recursively
%% ------------------------------------------------------------

if isempty(csvFiles)

    fprintf('No CSV files found in expected folder.\n');
    fprintf('Searching entire repository...\n\n');

    csvUpper = dir(fullfile(repoFolder, '**', '*.CSV'));
    csvLower = dir(fullfile(repoFolder, '**', '*.csv'));

    csvFiles = [csvUpper; csvLower];

end


%% ------------------------------------------------------------
% Remove files generated by this script
%% ------------------------------------------------------------

if ~isempty(csvFiles)

    keepFile = true(length(csvFiles), 1);

    for k = 1:length(csvFiles)

        fileNameLower = lower(csvFiles(k).name);

        if contains(fileNameLower, 'frequency_results') || ...
           contains(fileNameLower, 'identification_results')

            keepFile(k) = false;

        end

    end

    csvFiles = csvFiles(keepFile);

end


%% ============================================================
% 4. MATCH FILES TO FREQUENCIES
%% ============================================================

selectedFiles = cell(numberExpected, 1);


for fIndex = 1:numberExpected

    targetFrequency = expectedFrequencies(fIndex);

    foundFile = false;


    %% --------------------------------------------------------
    % Search available filenames
    %% --------------------------------------------------------

    for k = 1:length(csvFiles)

        [~, baseName, ~] = fileparts(csvFiles(k).name);

        % Extract a numerical value from filename
        numericText = regexp( ...
            baseName, ...
            '[-+]?\d*\.?\d+', ...
            'match', ...
            'once');

        if ~isempty(numericText)

            fileFrequency = str2double(numericText);

            if abs(fileFrequency - targetFrequency) < 1e-6

                selectedFiles{fIndex} = fullfile( ...
                    csvFiles(k).folder, ...
                    csvFiles(k).name);

                foundFile = true;

                break;

            end

        end

    end


    %% --------------------------------------------------------
    % Manual selection if a frequency file cannot be found
    %% --------------------------------------------------------

    if ~foundFile

        fprintf('\n');
        fprintf('Could not automatically find data for:\n');
        fprintf('omega = %.1f rad/s\n', targetFrequency);

        fprintf('Please select the corresponding CSV file.\n\n');


        [fileName, filePath] = uigetfile( ...
            {'*.CSV;*.csv', ...
            'CSV Files (*.CSV, *.csv)'}, ...
            sprintf( ...
            'Select %.1f rad/s Frequency Test CSV', ...
            targetFrequency), ...
            repoFolder);


        if isequal(fileName, 0)

            error( ...
                'No CSV selected for %.1f rad/s.', ...
                targetFrequency);

        end


        selectedFiles{fIndex} = ...
            fullfile(filePath, fileName);

    end

end


%% ============================================================
% 5. DISPLAY FILES BEING USED
%% ============================================================

fprintf('\n');
fprintf('Frequency files selected:\n');
fprintf('---------------------------------------------\n');


for k = 1:numberExpected

    fprintf( ...
        '%5.1f rad/s  ->  %s\n', ...
        expectedFrequencies(k), ...
        selectedFiles{k});

end


fprintf('\n');


%% ============================================================
% 6. PREALLOCATE RESULTS
%% ============================================================

inputAmplitude = zeros(numberExpected, 1);

outputAmplitude = zeros(numberExpected, 1);

magnitudeLinear = zeros(numberExpected, 1);

magnitudeDB = zeros(numberExpected, 1);

phaseRawDegrees = zeros(numberExpected, 1);

phaseCorrectedDegrees = zeros(numberExpected, 1);


%% ============================================================
% 7. SAMPLE TIME
%% ============================================================

% The laboratory manual states that data is logged every 100 ms.
sampleTime = 0.1;


%% ============================================================
% 8. PROCESS EACH FREQUENCY
%% ============================================================

for testIndex = 1:numberExpected

    omega = expectedFrequencies(testIndex);

    currentFile = selectedFiles{testIndex};


    fprintf( ...
        'Processing %.1f rad/s...\n', ...
        omega);


    %% --------------------------------------------------------
    % Read CSV
    %% --------------------------------------------------------

    try

        data = readtable( ...
            currentFile, ...
            'VariableNamingRule', ...
            'preserve');

    catch

        data = readtable(currentFile);

    end


    %% --------------------------------------------------------
    % Identify columns robustly
    %% --------------------------------------------------------

    variableNames = data.Properties.VariableNames;

    normalizedNames = lower( ...
        regexprep(variableNames, '[^a-zA-Z0-9]', ''));


    timeIndex = find( ...
        contains(normalizedNames, 'time'), ...
        1);


    inputIndex = find( ...
        contains(normalizedNames, 'input'), ...
        1);


    outputIndex = find( ...
        contains(normalizedNames, 'outputdisplacement'), ...
        1);


    if isempty(outputIndex)

        outputIndex = find( ...
            contains(normalizedNames, 'output'), ...
            1);

    end


    if isempty(timeIndex)
        error('Could not identify time column in %s', currentFile);
    end

    if isempty(inputIndex)
        error('Could not identify input column in %s', currentFile);
    end

    if isempty(outputIndex)
        error('Could not identify output column in %s', currentFile);
    end


    %% --------------------------------------------------------
    % Extract arrays
    %% --------------------------------------------------------

    t = data{:, timeIndex};
    u = data{:, inputIndex};
    y = data{:, outputIndex};


    t = t(:);
    u = u(:);
    y = y(:);


    %% --------------------------------------------------------
    % Remove invalid rows
    %% --------------------------------------------------------

    validRows = ...
        isfinite(t) & ...
        isfinite(u) & ...
        isfinite(y);


    t = t(validRows);
    u = u(validRows);
    y = y(validRows);


    %% --------------------------------------------------------
    % Find beginning of sinusoidal test
    %% --------------------------------------------------------

    activeIndex = find( ...
        abs(u) > 1e-5, ...
        1, ...
        'first');


    if isempty(activeIndex)

        error( ...
            'No sinusoidal input found in %s', ...
            currentFile);

    end


    %% --------------------------------------------------------
    % Period of sinusoid
    %% --------------------------------------------------------

    period = 2*pi / omega;


    %% --------------------------------------------------------
    % Ignore first four cycles
    %
    % This allows the transient component to decay before
    % estimating the steady-state sinusoidal response.
    %% --------------------------------------------------------

    analysisStartTime = ...
        t(activeIndex) + 4*period;


    analysisMask = ...
        t >= analysisStartTime;


    %% --------------------------------------------------------
    % Fallback if there are not enough samples after four cycles
    %% --------------------------------------------------------

    if sum(analysisMask) < 30

        fprintf( ...
            '  Warning: fewer than 30 samples after 4 cycles.\n');

        fprintf( ...
            '  Using final 60%% of available data instead.\n');


        firstFallbackIndex = ...
            round(0.40 * length(t));


        analysisMask = false(size(t));

        analysisMask(firstFallbackIndex:end) = true;

    end


    tFit = t(analysisMask);

    uFit = u(analysisMask);

    yFit = y(analysisMask);


    %% ========================================================
    % 9. LEAST-SQUARES SINUSOID FIT
    %
    % Signal:
    %
    % x(t) = C + A*sin(wt) + B*cos(wt)
    %
    % Amplitude:
    %
    % sqrt(A^2 + B^2)
    %
    % Phase:
    %
    % atan2(B,A)
    %% ========================================================

    X = [ ...
        ones(size(tFit)), ...
        sin(omega*tFit), ...
        cos(omega*tFit) ...
        ];


    inputCoefficients = ...
        X \ uFit;


    outputCoefficients = ...
        X \ yFit;


    %% --------------------------------------------------------
    % Input amplitude
    %% --------------------------------------------------------

    inputSin = inputCoefficients(2);

    inputCos = inputCoefficients(3);


    Ain = sqrt( ...
        inputSin^2 + ...
        inputCos^2);


    %% --------------------------------------------------------
    % Output amplitude
    %% --------------------------------------------------------

    outputSin = outputCoefficients(2);

    outputCos = outputCoefficients(3);


    Aout = sqrt( ...
        outputSin^2 + ...
        outputCos^2);


    %% --------------------------------------------------------
    % Input phase
    %% --------------------------------------------------------

    inputPhase = atan2( ...
        inputCos, ...
        inputSin);


    %% --------------------------------------------------------
    % Output phase
    %% --------------------------------------------------------

    outputPhase = atan2( ...
        outputCos, ...
        outputSin);


    %% ========================================================
    % 10. MAGNITUDE
    %% ========================================================

    gainLinear = ...
        Aout / Ain;


    gainDB = ...
        20*log10(gainLinear);


    %% ========================================================
    % 11. PHASE DIFFERENCE
    %% ========================================================

    rawPhase = ...
        rad2deg( ...
        outputPhase - inputPhase);


    %% --------------------------------------------------------
    % Wrap to -180 ... +180 degrees
    %% --------------------------------------------------------

    rawPhase = ...
        mod(rawPhase + 180, 360) - 180;


    %% --------------------------------------------------------
    % Convert output lead representation to equivalent lag
    %% --------------------------------------------------------

    if rawPhase > 0

        rawPhase = ...
            rawPhase - 360;

    end


    %% --------------------------------------------------------
    % Sampling-alignment correction
    %
    % Laboratory data is logged every 0.1 s.
    % A one-sample alignment difference corresponds to:
    %
    % phase correction = omega * Ts
    %
    % in radians.
    %% --------------------------------------------------------

    sampleCorrectionDegrees = ...
        omega * sampleTime * ...
        180/pi;


    correctedPhase = ...
        rawPhase + sampleCorrectionDegrees;


    %% --------------------------------------------------------
    % Save results
    %% --------------------------------------------------------

    inputAmplitude(testIndex) = Ain;

    outputAmplitude(testIndex) = Aout;

    magnitudeLinear(testIndex) = ...
        gainLinear;

    magnitudeDB(testIndex) = ...
        gainDB;

    phaseRawDegrees(testIndex) = ...
        rawPhase;

    phaseCorrectedDegrees(testIndex) = ...
        correctedPhase;


end


%% ============================================================
% 12. UNWRAP PHASE ACROSS FREQUENCIES
%% ============================================================

phaseRadians = ...
    deg2rad(phaseCorrectedDegrees);


phaseUnwrapped = ...
    unwrap(phaseRadians);


phaseDegrees = ...
    rad2deg(phaseUnwrapped);


%% ============================================================
% 13. CREATE RESULTS TABLE
%% ============================================================

frequencies = expectedFrequencies;


resultsTable = table( ...
    frequencies, ...
    inputAmplitude, ...
    outputAmplitude, ...
    magnitudeLinear, ...
    magnitudeDB, ...
    phaseRawDegrees, ...
    phaseDegrees, ...
    'VariableNames', { ...
    'Frequency_rad_s', ...
    'InputAmplitude', ...
    'OutputAmplitude', ...
    'MagnitudeLinear', ...
    'Magnitude_dB', ...
    'PhaseRaw_deg', ...
    'PhaseCorrected_deg' ...
    });


fprintf('\n');
fprintf('=============================================\n');
fprintf('MEASURED FREQUENCY RESPONSE\n');
fprintf('=============================================\n\n');


disp(resultsTable);


%% ============================================================
% 14. ESTIMATE LOW-FREQUENCY/DC GAIN
%% ============================================================

% Use lowest tested frequency as approximation to DC gain.
Kfreq = magnitudeLinear(1);


fprintf('\n');
fprintf('Frequency-domain DC gain estimate:\n');

fprintf( ...
    'K_freq = %.4f\n', ...
    Kfreq);


%% ============================================================
% 15. ESTIMATE NATURAL FREQUENCY FROM -90 DEG CROSSING
%% ============================================================

targetPhase = -90;


crossIndex = [];


for k = 1:(length(frequencies)-1)

    phase1 = phaseDegrees(k);

    phase2 = phaseDegrees(k+1);


    if (phase1 > targetPhase && phase2 <= targetPhase) || ...
       (phase1 < targetPhase && phase2 >= targetPhase)

        crossIndex = k;
        break;

    end

end


%% ------------------------------------------------------------
% Interpolate if crossing found
%% ------------------------------------------------------------

if ~isempty(crossIndex)

    w1 = frequencies(crossIndex);

    w2 = frequencies(crossIndex + 1);

    p1 = phaseDegrees(crossIndex);

    p2 = phaseDegrees(crossIndex + 1);


    omegaNfreq = ...
        w1 + ...
        (targetPhase - p1) * ...
        (w2 - w1) / ...
        (p2 - p1);


else

    %% --------------------------------------------------------
    % Fallback: choose measured point closest to -90 degrees
    %% --------------------------------------------------------

    fprintf('\n');
    fprintf('Warning: exact -90 degree crossing not found.\n');

    fprintf('Using closest measured phase point instead.\n');


    [~, closestIndex] = ...
        min(abs(phaseDegrees + 90));


    omegaNfreq = ...
        frequencies(closestIndex);

end


fprintf('\n');
fprintf('Estimated natural frequency from phase:\n');

fprintf( ...
    'wn_freq = %.4f rad/s\n', ...
    omegaNfreq);


%% ============================================================
% 16. INTERPOLATE MAGNITUDE AT NATURAL FREQUENCY
%% ============================================================

magnitudeAtWn = interp1( ...
    frequencies, ...
    magnitudeLinear, ...
    omegaNfreq, ...
    'linear', ...
    'extrap');


%% ============================================================
% 17. ESTIMATE DAMPING RATIO
%
% For:
%
%              K*wn^2
% G(s) = ----------------------
%         s^2 + 2*zeta*wn*s + wn^2
%
% At w = wn:
%
% |G(jwn)| = K/(2*zeta)
%
% Therefore:
%
% zeta = K/(2|G(jwn)|)
%% ============================================================

zetaFreq = ...
    Kfreq / ...
    (2 * magnitudeAtWn);


fprintf('\n');
fprintf('Estimated damping ratio from frequency test:\n');

fprintf( ...
    'zeta_freq = %.4f\n', ...
    zetaFreq);


%% ============================================================
% 18. BUILD FREQUENCY-DOMAIN TRANSFER FUNCTION
%% ============================================================

numFreq = ...
    Kfreq * omegaNfreq^2;


denFreqS = ...
    2 * zetaFreq * omegaNfreq;


denFreqConstant = ...
    omegaNfreq^2;


Gfreq = tf( ...
    numFreq, ...
    [1 denFreqS denFreqConstant]);


polesFreq = ...
    pole(Gfreq);


fprintf('\n');
fprintf('=============================================\n');
fprintf('FREQUENCY-DOMAIN MODEL\n');
fprintf('=============================================\n\n');


Gfreq


fprintf('Poles:\n');

disp(polesFreq);


%% ============================================================
% 19. STEP-TEST MODEL FOR COMPARISON
%% ============================================================

% Values obtained independently from the step test

Kstep = 0.6380;

zetaStep = 0.7455;

omegaNstep = 1.8129;


numStep = ...
    Kstep * omegaNstep^2;


denStepS = ...
    2 * zetaStep * omegaNstep;


denStepConstant = ...
    omegaNstep^2;


Gstep = tf( ...
    numStep, ...
    [1 denStepS denStepConstant]);


fprintf('\n');
fprintf('=============================================\n');
fprintf('STEP-DOMAIN MODEL\n');
fprintf('=============================================\n\n');


Gstep


%% ============================================================
% 20. CREATE COMBINED/AVERAGED MODEL
%% ============================================================

Kfinal = ...
    (Kstep + Kfreq) / 2;


zetaFinal = ...
    (zetaStep + zetaFreq) / 2;


omegaNfinal = ...
    (omegaNstep + omegaNfreq) / 2;


numFinal = ...
    Kfinal * omegaNfinal^2;


denFinalS = ...
    2 * zetaFinal * omegaNfinal;


denFinalConstant = ...
    omegaNfinal^2;


Gfinal = tf( ...
    numFinal, ...
    [1 denFinalS denFinalConstant]);


polesFinal = ...
    pole(Gfinal);


fprintf('\n');
fprintf('=============================================\n');
fprintf('FINAL COMBINED MODEL\n');
fprintf('=============================================\n\n');


Gfinal


fprintf('Final poles:\n');

disp(polesFinal);


%% ============================================================
% 21. CHECK FOR RESONANCE PEAK
%% ============================================================

fprintf('\n');
fprintf('=============================================\n');
fprintf('RESONANCE CHECK\n');
fprintf('=============================================\n\n');


resonanceLimit = ...
    1/sqrt(2);


fprintf( ...
    'Estimated frequency-test zeta = %.4f\n', ...
    zetaFreq);


fprintf( ...
    'Resonance threshold           = %.4f\n\n', ...
    resonanceLimit);


if zetaFreq < resonanceLimit

    omegaResonance = ...
        omegaNfreq * ...
        sqrt(1 - 2*zetaFreq^2);


    fprintf('A Bode resonance peak is expected.\n');

    fprintf( ...
        'Estimated resonance frequency = %.4f rad/s\n', ...
        omegaResonance);

else

    fprintf('No Bode resonance peak is expected.\n');

    fprintf([ ...
        'The system can still be underdamped and have\n' ...
        'step-response overshoot because zeta < 1.\n']);

end


%% ============================================================
% 22. SMOOTH MODEL FREQUENCY VECTOR
%% ============================================================

omegaModel = logspace( ...
    log10(0.3), ...
    log10(10), ...
    600);


%% ============================================================
% 23. STEP-MODEL FREQUENCY RESPONSE
%% ============================================================

responseStep = squeeze( ...
    freqresp( ...
    Gstep, ...
    omegaModel));


magnitudeStepDB = ...
    20*log10(abs(responseStep));


phaseStep = ...
    rad2deg( ...
    unwrap(angle(responseStep)));


%% ============================================================
% 24. FREQUENCY-MODEL RESPONSE
%% ============================================================

responseFreq = squeeze( ...
    freqresp( ...
    Gfreq, ...
    omegaModel));


magnitudeFreqDB = ...
    20*log10(abs(responseFreq));


phaseFreq = ...
    rad2deg( ...
    unwrap(angle(responseFreq)));


%% ============================================================
% 25. FINAL-MODEL RESPONSE
%% ============================================================

responseFinal = squeeze( ...
    freqresp( ...
    Gfinal, ...
    omegaModel));


magnitudeFinalDB = ...
    20*log10(abs(responseFinal));


phaseFinal = ...
    rad2deg( ...
    unwrap(angle(responseFinal)));


%% ============================================================
% 26. MAGNITUDE BODE PLOT
%% ============================================================

figure('Name', ...
    'Frequency Response Magnitude');


semilogx( ...
    frequencies, ...
    magnitudeDB, ...
    'o', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.6);


hold on;


semilogx( ...
    omegaModel, ...
    magnitudeStepDB, ...
    '--', ...
    'LineWidth', ...
    1.5);


semilogx( ...
    omegaModel, ...
    magnitudeFreqDB, ...
    '-.', ...
    'LineWidth', ...
    1.5);


semilogx( ...
    omegaModel, ...
    magnitudeFinalDB, ...
    '-', ...
    'LineWidth', ...
    1.8);


xline( ...
    omegaNfreq, ...
    ':', ...
    sprintf( ...
    '\\omega_n = %.2f rad/s', ...
    omegaNfreq));


grid on;


xlabel( ...
    'Angular Frequency, \omega (rad/s)');


ylabel( ...
    'Magnitude (dB)');


title( ...
    'Measured and Modelled Frequency Response - Magnitude');


legend( ...
    'Measured data', ...
    'Step-test model', ...
    'Frequency-test model', ...
    'Final combined model', ...
    'Estimated natural frequency', ...
    'Location', ...
    'southwest');


%% ------------------------------------------------------------
% Save magnitude figure
%% ------------------------------------------------------------

magnitudeFigureFile = ...
    fullfile( ...
    figureFolder, ...
    'bode_magnitude_matlab.png');


try

    exportgraphics( ...
        gcf, ...
        magnitudeFigureFile, ...
        'Resolution', ...
        300);

catch

    saveas( ...
        gcf, ...
        magnitudeFigureFile);

end


%% ============================================================
% 27. PHASE BODE PLOT
%% ============================================================

figure('Name', ...
    'Frequency Response Phase');


semilogx( ...
    frequencies, ...
    phaseDegrees, ...
    'o', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.6);


hold on;


semilogx( ...
    omegaModel, ...
    phaseStep, ...
    '--', ...
    'LineWidth', ...
    1.5);


semilogx( ...
    omegaModel, ...
    phaseFreq, ...
    '-.', ...
    'LineWidth', ...
    1.5);


semilogx( ...
    omegaModel, ...
    phaseFinal, ...
    '-', ...
    'LineWidth', ...
    1.8);


yline( ...
    -90, ...
    ':', ...
    '-90 degrees');


xline( ...
    omegaNfreq, ...
    ':', ...
    sprintf( ...
    '\\omega_n = %.2f rad/s', ...
    omegaNfreq));


grid on;


xlabel( ...
    'Angular Frequency, \omega (rad/s)');


ylabel( ...
    'Phase (degrees)');


title( ...
    'Measured and Modelled Frequency Response - Phase');


legend( ...
    'Measured data', ...
    'Step-test model', ...
    'Frequency-test model', ...
    'Final combined model', ...
    '-90 degree phase', ...
    'Estimated natural frequency', ...
    'Location', ...
    'southwest');


%% ------------------------------------------------------------
% Save phase figure
%% ------------------------------------------------------------

phaseFigureFile = ...
    fullfile( ...
    figureFolder, ...
    'bode_phase_matlab.png');


try

    exportgraphics( ...
        gcf, ...
        phaseFigureFile, ...
        'Resolution', ...
        300);

catch

    saveas( ...
        gcf, ...
        phaseFigureFile);

end


%% ============================================================
% 28. SAVE EXPERIMENTAL RESULTS TABLE
%% ============================================================

resultsOutputFile = ...
    fullfile( ...
    dataFolder, ...
    'frequency_results_matlab.csv');


if ~exist(dataFolder, 'dir')

    mkdir(dataFolder);

end


writetable( ...
    resultsTable, ...
    resultsOutputFile);


%% ============================================================
% 29. CREATE MODEL SUMMARY TABLE
%% ============================================================

Model = { ...
    'Step Test'
    'Frequency Test'
    'Final Combined Model'
    };


DC_Gain = [ ...
    Kstep
    Kfreq
    Kfinal
    ];


Damping_Ratio = [ ...
    zetaStep
    zetaFreq
    zetaFinal
    ];


Natural_Frequency_rad_s = [ ...
    omegaNstep
    omegaNfreq
    omegaNfinal
    ];


Numerator = [ ...
    numStep
    numFreq
    numFinal
    ];


Denominator_s = [ ...
    denStepS
    denFreqS
    denFinalS
    ];


Denominator_constant = [ ...
    denStepConstant
    denFreqConstant
    denFinalConstant
    ];


modelSummary = table( ...
    Model, ...
    DC_Gain, ...
    Damping_Ratio, ...
    Natural_Frequency_rad_s, ...
    Numerator, ...
    Denominator_s, ...
    Denominator_constant);


modelSummaryFile = ...
    fullfile( ...
    dataFolder, ...
    'model_comparison_matlab.csv');


writetable( ...
    modelSummary, ...
    modelSummaryFile);


%% ============================================================
% 30. PRINT FINAL RESULTS
%% ============================================================

fprintf('\n');
fprintf('=============================================\n');
fprintf('SUMMARY OF IDENTIFICATION RESULTS\n');
fprintf('=============================================\n\n');


fprintf('STEP TEST\n');

fprintf( ...
    'K       = %.4f\n', ...
    Kstep);

fprintf( ...
    'zeta    = %.4f\n', ...
    zetaStep);

fprintf( ...
    'wn      = %.4f rad/s\n\n', ...
    omegaNstep);


fprintf('FREQUENCY TEST\n');

fprintf( ...
    'K       = %.4f\n', ...
    Kfreq);

fprintf( ...
    'zeta    = %.4f\n', ...
    zetaFreq);

fprintf( ...
    'wn      = %.4f rad/s\n\n', ...
    omegaNfreq);


fprintf('FINAL COMBINED MODEL\n');

fprintf( ...
    'K       = %.4f\n', ...
    Kfinal);

fprintf( ...
    'zeta    = %.4f\n', ...
    zetaFinal);

fprintf( ...
    'wn      = %.4f rad/s\n', ...
    omegaNfinal);


fprintf('\n');

fprintf('Final numerator              = %.4f\n', ...
    numFinal);

fprintf('Final denominator s term     = %.4f\n', ...
    denFinalS);

fprintf('Final denominator constant   = %.4f\n', ...
    denFinalConstant);


fprintf('\nFinal transfer function:\n\n');

Gfinal


fprintf('Final poles:\n\n');

disp(polesFinal);


%% ============================================================
% 31. PRINT MEASURED BODE TABLE
%% ============================================================

fprintf('\n');
fprintf('=============================================\n');
fprintf('MEASURED BODE DATA\n');
fprintf('=============================================\n\n');


fprintf( ...
    ' omega     Gain(dB)      Phase(deg)\n');

fprintf( ...
    '-----------------------------------\n');


for k = 1:numberExpected

    fprintf( ...
        '%5.1f      %8.2f       %8.2f\n', ...
        frequencies(k), ...
        magnitudeDB(k), ...
        phaseDegrees(k));

end


%% ============================================================
% 32. FINISHED
%% ============================================================

fprintf('\n');
fprintf('=============================================\n');
fprintf('ANALYSIS COMPLETE\n');
fprintf('=============================================\n\n');


fprintf('Magnitude figure saved to:\n%s\n\n', ...
    magnitudeFigureFile);


fprintf('Phase figure saved to:\n%s\n\n', ...
    phaseFigureFile);


fprintf('Processed frequency data saved to:\n%s\n\n', ...
    resultsOutputFile);


fprintf('Model comparison saved to:\n%s\n\n', ...
    modelSummaryFile);


fprintf(['Your measured magnitude should decrease smoothly\n' ...
         'without a strong resonance peak because your\n' ...
         'estimated damping ratio is approximately 0.74.\n\n']);